MyBlog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from apps.user.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('user/', include(('apps.user.urls', 'apps.user'), namespace='user')),
    url(r'^article/', include(('apps.article.urls', 'apps.article'), namespace='article'))
]

apps/article/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^post', views.upload_article, name='post'),
    url(r'^show', views.show_blog, name='show')
]

apps/user/urls.py
from django.urls import path

from . import views
from .views import *

urlpatterns = [
    path('register/', user_register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('retrieve/', user_retrieve, name='retrieve'),
    path('center/', user_center, name='center'),
    path('reset/', views.reset_password, name='reset'),
]

apps/article/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

from apps.user.models import UserProfile


class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='标签')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tag'
        verbose_name = '标签表'
        verbose_name_plural = verbose_name


class Article(models.Model):
    created_date = models.DateTimeField(default=timezone.now, verbose_name='发布时间')
    updated_date = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    content = models.CharField(max_length=140, verbose_name='内容')
    liked_num = models.IntegerField(default=0, verbose_name='点赞数')
    visited_num = models.IntegerField(default=0, verbose_name='浏览量')
    image = models.CharField(max_length=200, verbose_name='图片地址')

    tags = models.ManyToManyField(to=Tag)
    author = models.ForeignKey(to=UserProfile, on_delete=models.CASCADE, verbose_name='发布者id')

    def __unicode__(self):
        return self.content

    class Meta:
        db_table = 'article'
        verbose_name = '文章表'
        verbose_name_plural = verbose_name

apps/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class UserProfile(AbstractUser):
    phone_number = models.CharField(max_length=11, verbose_name='电话号码', unique=True)
    user_avatar = models.CharField(max_length=500, verbose_name='头像地址')
    user_desc = models.CharField(max_length=140, verbose_name='个人信息')

    class Meta:
        db_table = 'user_profile'
        verbose_name = '用户表'
        verbose_name_plural = verbose_name

apps/article/forms.py
from django import forms
from django.forms import Form


class UserPost(Form):
    author = forms.CharField(max_length=50, min_length=6, error_messages={'min_length': '用户名长度至少6位'})
    content = forms.CharField(max_length=140)

apps/user/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form

from apps.user.models import UserProfile


class UserRegisterForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['username', 'phone_number', 'email', 'password']


class UserLoginForm(Form):
    username = forms.CharField(max_length=50, min_length=6, error_messages={'min_length': '用户名长度至少6位'})
    password = forms.CharField(required=True, error_messages={'required': '必须填写密码'},
                               widget=forms.widgets.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not UserProfile.objects.filter(username=username).exists():
            raise ValidationError('用户名不存在')
        return username

apps/article/views.py
# Create your views here.
from datetime import date

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_POST

from apps.article.models import Article
from apps.user.models import UserProfile


def check_user(func):
    def inner(*args, **kwargs):
        username = args[0].session.get("username", "")
        if username == "":
            args[0].session['path'] = args[0].path
            return redirect(reverse("user:login"))
        return func(*args, **kwargs)

    return inner


@check_user
def upload_article(request):
    print(request)
    author = request.GET.get('author')
    user = UserProfile.objects.filter(username=author).first()
    content = request.GET.get('content')
    blog = Article.objects.create(content=content, author=user)
    if blog:
        data = {'status': 1}
    else:
        data = {'status': 0}
    return JsonResponse(data)


def show_blog(request):
    data = {}
    articles = Article.objects.values()
    data['list'] = list(articles)
    return JsonResponse(data)

apps/user/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from apps.article.models import Article
from apps.user.forms import UserRegisterForm, UserLoginForm
from apps.user.models import UserProfile


def index(request):
    articles = Article.objects.all().order_by('-created_date')
    return render(request, 'index.html', context={'articles': articles})


def user_register(request):
    if request.method == 'GET':
        return render(request, 'user/sign-up.html')
    else:
        rform = UserRegisterForm(request.POST)
        if rform.is_valid():
            username = rform.cleaned_data.get('username')
            email = rform.cleaned_data.get('email')
            phone_number = rform.cleaned_data.get('phone_number')
            password = rform.cleaned_data.get('password')
            if not UserProfile.objects.filter(
                    Q(username=username) | Q(email=email) | Q(phone_number=phone_number)).exists():
                password = make_password(password)
                user = UserProfile.objects.create(username=username, phone_number=phone_number, email=email,
                                                  password=password)
                if user:
                    return render(request, 'user/sign-in.html', context={'msg': '注册成功，请登录'})
            else:
                return render(request, 'user/sign-up.html', context={'msg': '用户已存在'})
        return render(request, 'user/sign-up.html', context={'msg': '用户注册失败'})


def user_login(request):
    if request.method == 'GET':
        return render(request, 'user/sign-in.html')
    else:
        lform = UserLoginForm(request.POST)
        if lform.is_valid():
            username = lform.cleaned_data.get('username')
            password = lform.cleaned_data.get('password')
            user = UserProfile.objects.filter(username=username).first()
            flag = check_password(password, user.password)
            # print(flag)
            if flag:
                request.session['username'] = username
                request.session['user_avatar'] = user.user_avatar
                request.session['desc'] = user.user_desc
                return redirect(reverse('index'))
            else:
                msg = '密码错误'
                return render(request, 'user/sign-in.html', context={'msg': msg})
        return render(request, 'user/sign-in.html', context={'errors': lform.errors})


def user_logout(request):
    request.session.flush()
    return redirect(reverse('index'))


def user_retrieve(request):
    if request.method == 'GET':
        return render(request, 'user/forgot-password.html')
    else:
        return HttpResponse(request.POST.get('email-or-tel'))


def user_center(request):
    return HttpResponse("用户中心")


def reset_password(request):
    return render(request, 'user/reset-password.html')


def post_blog(request):
    if request.method == 'GET':
        return redirect(reverse('index'))
    else:
        pass #TODO post微博

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}
        首页
    {% endblock %}</title>
    <!-- Slick Slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/slick/slick.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/slick/slick-theme.min.css' %}"/>
    <!-- Feather Icon-->
    <link href="{% static 'vendor/icons/feather.css' %} " rel="stylesheet" type="text/css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block mycss %}

    {% endblock %}
</head>
<body>
    <!--顶部状态栏-->
    {% block body_content %}

    {% endblock %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- slick Slider JS-->
    <script type="text/javascript" src="{% static 'vendor/slick/slick.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <!--<script src="{% static 'js/osahan.js' %}"></script>-->
    <script src="{% static 'js/drag_element.js' %}"></script>
    <script src="{% static 'vendor/vue/vue.min.js' %}"></script>
    <script src="{% static 'vendor/axios/axios.min.js' %}"></script>
    {% block myjs %}

    {% endblock %}
</body>
</html>

templates/base_index.html
{% extends 'base.html' %}
{% load static %}
{% block body_content %}
    <nav class="navbar navbar-expand navbar-dark bg-dark osahan-nav-top p-0">
        <div class="container">
            <!--图标和搜索框//TODO-->
            <a class="navbar-brand mr-2" href="{% url 'index' %}"><img style="width:38px;height: 38px;" alt=""
                                                                src={% static 'img/logo1.png' %}>
            </a>
            <form class="d-none d-sm-inline-block form-inline mr-auto my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control shadow-none border-0" placeholder="搜索博客"
                           aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn" type="button">
                            <i class="feather-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <!--顶部状态栏//TODO-->
            <ul class="navbar-nav ml-auto d-flex align-items-center">
                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="feather-search mr-2"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow-sm animated--grow-in"
                         aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control border-0 shadow-none"
                                       placeholder="Search blog..." aria-label="Search" aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn" type="button">
                                        <i class="feather-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="jobs.html"><i class="feather-user mr-2"></i><span
                            class="d-none d-lg-inline">个人中心</span></a>
                </li>
                <li class="nav-item dropdown mr-2">
                    <a class="nav-link dropdown-toggle pr-0" href="#" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="feather-file-text mr-2"></i><span class="d-none d-lg-inline">Pages</span>
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow-sm">
                        <a class="dropdown-item" href="jobs.html"><i class="feather-briefcase mr-1"></i> Jobs</a>
                        <a class="dropdown-item" href="profile.html"><i class="feather-user mr-1"></i> Profile</a>
                        <a class="dropdown-item" href="connection.html"><i class="feather-users mr-1"></i>
                            Connection</a>
                        <a class="dropdown-item" href="company-profile.html"><i class="feather-user-plus mr-1"></i>
                            Company Profile</a>
                        <a class="dropdown-item" href="job-profile.html"><i class="feather-globe mr-1"></i> Job Profile</a>
                        <a class="dropdown-item" href="user/sign-in.html"><i class="feather-log-in mr-1"></i> Sign
                            In</a>
                        <a class="dropdown-item" href="user/sign-up.html"><i class="feather-lock mr-1"></i> Sign Up</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1 osahan-list-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="feather-message-square"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-danger badge-counter">8</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-sm">
                        <h6 class="dropdown-header">
                            Message Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img alt="" class="rounded-circle" src={% static 'img/p1.png' %}>
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div class="font-weight-bold overflow-hidden">
                                <div class="text-truncate">Hi there! I am wondering if you can help me with a problem
                                    I've been having.
                                </div>
                                <div class="small text-gray-500">Emily Fowler · 58m</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img alt="" class="rounded-circle" src={% static 'img/p2.png' %}>
                                <div class="status-indicator"></div>
                            </div>
                            <div class="overflow-hidden">
                                <div class="text-truncate">I have the photos that you ordered last month, how would you
                                    like them sent to you?
                                </div>
                                <div class="small text-gray-500">Jae Chun · 1d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src={% static 'img/p3.png' %} alt="">
                                <div class="status-indicator bg-warning"></div>
                            </div>
                            <div class="overflow-hidden">
                                <div class="text-truncate">Last month's report looks great, I am very happy with the
                                    progress so far, keep up the good work!
                                </div>
                                <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img class="rounded-circle" src={% static 'img/p4.png' %} alt="">
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div class="overflow-hidden">
                                <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me
                                    that people say this to all dogs, even if they aren't good...
                                </div>
                                <div class="small text-gray-500">Chicken the Dog · 2w</div>
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1 osahan-list-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="feather-bell"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-info badge-counter">6</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-sm">
                        <h6 class="dropdown-header">
                            Alerts Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                    <i class="feather-download-cloud text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 12, 2019</div>
                                <span class="font-weight-bold">A new monthly report is ready to download!</span>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-success">
                                    <i class="feather-edit text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 7, 2019</div>
                                $290.29 has been deposited into your account!
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                    <i class="feather-folder text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 2, 2019</div>
                                Spending Alert: We've noticed unusually high spending for your account.
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                </li>
                <!-- Nav Item - User Information -->
                {% if request.session.username %}
                    <li class="nav-item dropdown no-arrow ml-1 osahan-profile-dropdown">
                        <a class="nav-link dropdown-toggle pr-0" href="#" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <img class="img-profile rounded-circle" src="https://danbooru.donmai.us/data/__original_drawn_by_kuroi_liar_player__2008844c97e06f63037267367d206e97.jpg">
                        </a>
                        <!-- Dropdown - User Information -->

                        <div class="dropdown-menu dropdown-menu-right shadow-sm">
                            <div class="p-3 d-flex align-items-center">
                                <div class="dropdown-list-image mr-3">
                                    <img alt="" class="rounded-circle" src="https://danbooru.donmai.us/data/__original_drawn_by_kuroi_liar_player__2008844c97e06f63037267367d206e97.jpg">
                                    <div class="status-indicator bg-success"></div>
                                </div>
                                <div class="font-weight-bold">
                                    <div class="text-truncate">{{ request.session.username }}</div>
                                    <div class="small text-gray-500">User</div>
                                </div>
                            </div>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'user:center' %}"><i class="feather-user mr-1"></i> 个人信息</a>
                            <a class="dropdown-item" href="{% url 'user:logout' %}"><i class="feather-log-out mr-1"></i>登出</a>
                        </div>
                    </li>
                {% else %}
                    <a href="{% url 'user:login' %}">
                        <button class="btn btn-primary btn-block text-uppercase" >登录</button>
                    </a>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="py-4">
        <div class="container">
            <div class="row">
                <!-- Main Content -->
                <main class="col col-xl-8 order-xl-2 col-lg-12 order-lg-1 col-md-12 col-sm-12 col-12">
                    {% block main_content %}

                    {% endblock %}
                </main>
                <!--左边栏//TODO-->
                <aside class="col col-xl-3 order-xl-1 col-lg-6 order-lg-2 col-md-6 col-sm-6 col-12">
                    {% block aside_content %}

                    {% endblock %}
                </aside>

            </div>
        </div>
    </div>
{% endblock %}

templates/user/forgot-password.html
{% extends 'base.html' %}
{% load static %}
{% block body_content %}
    <div class="bg-white">
        <div class="container">
            <div class="row justify-content-center align-items-center d-flex vh-100">
                <div class="col-md-4 mx-auto">
                    <div class="osahan-login py-4">
                        <div class="text-center mb-4">
                            <a href="{% url 'index' %}"><img src="{% static 'img/favicon.ico' %}" alt=""></a>
                            <h5 class="font-weight-bold mt-3">首先，让我们来找回您的账号</h5>
                            <p class="text-muted">请输入您的邮箱或手机号</p>
                        </div>

                        <form action="{% url 'user:retrieve' %}" onsubmit="return validate_form(this);"
                              method="post">{% csrf_token %}
                            <div class="form-group">
                                <label class="mb-1">邮箱或手机号</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-user position-absolute"></i>
                                    <input type="text" id="find-pwd-way" name="email-or-tel"  class="form-control">
                                </div>
                            </div>
                            <button class="btn btn-primary btn-block text-uppercase" id="submit-data" type="submit"> 找回账号</button>
                            <div class="py-3 d-flex align-item-center">
                                <a href="{% url 'user:login' %}">登录</a>
                                <span class="ml-auto"> 还没有账号？ <a class="font-weight-bold"
                                                                 href="{% url 'user:register' %}">注册</a></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block myjs %}
    <script>
        window.onload = function () {
              document.getElementById('submit-data').onsubmit = checkValidation;
        };
        function checkValidation() {
            let res = document.getElementById('find-pwd-way').value;
            console.log(res);
            let re = /^1[0-9]{10}/;
            if (!re.test(res)) {
                let reg = /[a-zA-Z0-9]{1,10}@[a-zA-Z0-9]{1,5}\.[a-zA-Z0-9]{1,5}/;
                if (!reg.test(res)) {
                    document.getElementById('find-pwd-way').setCustomValidity("请输入正确的邮箱号或手机号");
                } else {
                    console.log("邮箱")
                }
            } else {
                console.log("手机")
            }
        }
    </script>
{% endblock %}

templates/user/reset-password.html
{% extends 'base.html' %}
{% load static %}
{% block body_content %}
    <div class="bg-white">
        <div class="container">
            <div class="row justify-content-center align-items-center d-flex vh-100">
                <div class="col-md-4 mx-auto">
                    <div class="osahan-login py-4">
                        <div class="text-center mb-4">
                            <a href="{% url 'index' %}"><img src="{% static 'img/favicon.ico' %}" alt=""></a>
                            <h5 class="font-weight-bold mt-3"></h5>
                            <p class="text-muted">请重新输入密码</p>
                        </div>

                        <form action="{% url 'user:login' %}" method="post">{% csrf_token %}
                            <div class="form-group">
                                <label class="mb-1">密码</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-lock position-absolute"></i>
                                    <input type="password" id="pw1" name="password" required="" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="mb-1">确认密码</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-lock position-absolute"></i>
                                    <input type="password" id="pw2" name="password" required="" class="form-control">
                                </div>
                            </div>
                            <button class="btn btn-primary btn-block text-uppercase" id="submit-data" type="submit">确认</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/sign-in.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    用户登录
{% endblock %}
{% block body_content %}
    <div class="bg-white">
         <div class="container">
            <div class="row justify-content-center align-items-center d-flex vh-100">
               <div class="col-md-4 mx-auto">
                  <div class="osahan-login py-4">
                     <div class="text-center mb-4">
                        <a href="{% url 'index' %}"><img alt="" src="{% static 'img/favicon.ico' %}" ></a>
                        <h5 class="font-weight-bold mt-3">欢迎回来</h5>
                        <p class="text-muted">期待与你一起分享美丽的世界</p>
                         <p class="text-danger ">{{ msg }}{{ errors }}</p>
                     </div>
                     <form action="{% url 'user:login' %}" method="post" >{% csrf_token %}
                        <div class="form-group">
                           <label class="mb-1">用户名</label>
                           <div class="position-relative icon-form-control">
                              <i class="feather-user position-absolute"></i>
                              <input type="text" name="username" class="form-control" required="">
                           </div>
                        </div>
                        <div class="form-group">
                           <label class="mb-1">密码</label>
                           <div class="position-relative icon-form-control">
                              <i class="feather-unlock position-absolute"></i>
                              <input type="password" name="password" class="form-control" required="">
                           </div>
                        </div>
                        <div class="custom-control custom-checkbox mb-3">
                           <input type="checkbox" class="custom-control-input" id="customCheck1">
                           <label class="custom-control-label" for="customCheck1">记住密码</label>
                        </div>
                         <button class="btn btn-primary btn-block text-uppercase" type="submit" name="login">登录</button>

                        <div class="py-3 d-flex align-item-center">
                           <a href="{% url 'user:retrieve' %}">忘记密码？</a>
                           <span class="ml-auto"> 还没有账号？ <a class="font-weight-bold" href="{% url 'user:register' %}">注册</a></span>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
{% endblock %}